# Generated by Django 3.2.6 on 2021-08-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moded_date',
            field=models.DateTimeField(null=True),
        ),
    ]
