# Generated by Django 3.2.6 on 2021-08-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_moded_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='moded_date',
            new_name='modded_date',
        ),
    ]
