# Generated by Django 3.2.6 on 2021-08-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_moded_date_product_modded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
