# Generated by Django 3.2.6 on 2021-08-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_modded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
