# Generated by Django 3.2.6 on 2021-08-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210828_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='downvote',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='upvote',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
