# Generated by Django 3.2.6 on 2021-08-28 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20210828_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='product',
            name='upvote',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_author', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='downvotes',
            field=models.ManyToManyField(related_name='product_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='upvotes',
            field=models.ManyToManyField(related_name='product_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
