# Generated by Django 3.2.6 on 2021-08-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210830_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomizableinfo',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='../static'),
        ),
    ]
