# Generated by Django 3.2.6 on 2021-08-30 14:58

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210830_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomizableinfo',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='usercustomizableinfo',
            name='img_width',
        ),
        migrations.AlterField(
            model_name='usercustomizableinfo',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=common.models.user_directory_path),
        ),
    ]
